server:
  port: ${PORT}

eureka:
  instance:
    hostname: ${HOST}
  client:
    serviceUrl.defaultZone: ${SERVICE_DISCOVERER_URL}/eureka/
    registerWithEureka: false
    fetchRegistry: false

spring.config.import: optional:configserver:${CONFIG_SERVER_URL}
